### ISSUE TITLE
Setting the icon path

### ISSUE THREAD

**Issue by kmmathis** [nathanpalmer/example-semantic-ui-ember-cli#1]
I was playing around with this repo trying to figure out how to customize Semantic UI in my own Ember app, and noticed that the icon path isn't correctly set.

The CSS is trying to load the font from here:

```
http://localhost:4200/themes/default/assets/fonts/
```

But the files are actually located here:

```
http://localhost:4200/assets/themes/default/assets/fonts/
```

I'm not exactly sure how to fix this. Is it as simple overriding the font path somewhere?

**Comment by kmmathis** [comment]
I've actually decided to just build a custom version of semantic.css with gulp and pull it in to my project. The build times with ember-cli and the less compiler were just too long.

**Comment by dfmarulanda** [comment]
Did you find a solution to this?
